<?php
require 'controlador/conecta.php';
$query     = "SELECT  ID_EMPLEADO, ID_TIPO_EMPLEADO, RUT_EMPLEADO, NOMBRES_EMPLEADO, APELLIDOPATER_EMPLEADO, APELLIDOMATER_EMPLEADO, FECHA_NACIMIENTO, GENERO_EMPLEADO, DIRECCION_EMPLEADO, FONO_EMPLEADO, EMAIL_EMPLEADO  FROM templeado order by RUT_EMPLEADO ASC";
$resultado = $mysqli->query($query);
